thephpleague/omnipay-common

.gitignore, makedoc.sh, src/Omnipay/Common/AbstractGateway.php, src/Omnipay/Common/CreditCard.php, src/Omnipay/Common/Currency.php, src/Omnipay/Common/GatewayFactory.php, src/Omnipay/Common/GatewayInterface.php, src/Omnipay/Common/Helper.php, src/Omnipay/Common/Issuer.php, src/Omnipay/Common/Item.php, src/Omnipay/Common/ItemBag.php, src/Omnipay/Common/ItemInterface.php, src/Omnipay/Common/PaymentMethod.php, src/Omnipay/Omnipay.php
I have added some documentation to the Omnipay common classes to conform with the PHPDoc standard.  Reference: http://www.phpdoc.org/docs/latest/references/phpdoc/index.html and http://phpdoc.org/docs/latest/getting-started/your-first-set-of-documentation.html (which I find to be a useful guide).
I have also added a simple API documentation generation script assuming that the "apidoc" executable is somewhere on the system. This might be of some use to developers while working on the classes or generating API documentation.
Please feel free to accept or ignore this PR. If you don't feel the need for expanded API documentation and docblocks for Omnipay then just drop the PR, otherwise if you accept it I will continue to add more PRs to improve the docblocks in this area as well as the other …
=> Adding documentation, adding documentation generation script

src/Omnipay/Common/CreditCard.php, tests/Omnipay/Common/CreditCardTest.php
Or else, one can validate that `43` is a valid credit credit card number.
=> Ensure short number cannot be considered as valid credit card number

.travis.yml, composer.json
Composer shows warnings in any project requiring omnipay-common, since guzzle/http is abandoned and no longer supported. This is not nice, esp. since this might introduce some security issues in future.
=> Change abandoned guzzle/http to guzzle/guzzle (fixes #33)

src/Omnipay/Common/Helper.php, src/Omnipay/Common/Message/AbstractRequest.php, tests/Omnipay/Common/HelperTest.php, tests/Omnipay/Common/Message/AbstractRequestTest.php
Being more consistent with the amount: getAmount() will always return a formatted string. Some additional checks on the format of the value passed in (floats, integers and strings are allowed, so long as their value is unambiguous - integers still not accepted for currencies that support decimals, for legacy reasons).
Zero amounts now explicitly allowed, and negative amounts checked for. However, both of these can be reversed by overriding the appropriate properties.
Decimal point is still always "." regardless of locale. This is derived from the PHP format for floats, which always uses a ".". Any gateway that needs to send other decimal characters to the remote gateway, will need to overwrite getAmount().
=> Issue #17 and Issue #13

src/Omnipay/Omnipay.php
phpcs (run by travis-ci) errors out on lines >120 characters.
Suppress this check for this long phpdoc tag line.
=> Suppress line length check on long phpdoc line

src/Omnipay/Common/Message/AbstractResponse.php
If some form values are UTF-8 encoded (example: greek characters) then the submitted content is garbled.
=> Redirect message page should use UTF-8 charset

src/Omnipay/Common/AbstractGateway.php, src/Omnipay/Common/Message/NotificationInterface.php, tests/Omnipay/Common/AbstractGatewayTest.php
This is the companion pull request to thephpleague/omnipay#215.
=> Add interfaces for incoming notifications

src/Omnipay/Common/Helper.php, tests/Omnipay/Common/HelperTest.php
For example, this will allow you pass $_SERVER to the gateway and create specific getters/setters for keys such as "HTTP_ACCEPT".
=> Adding support for getter/setter created for values made up of all caps and underscores.

src/Omnipay/Common/GatewayInterface.php
This should help IDE's with code completion and suggestions on the gateway methods and return values (which doesn't work very well at the moment).
I understand that these methods are optional - so this may not be the right way to address this issue. My personal opinion is that documenting the method as optional in the annotation is better than not documenting it all.
There are also lots of methods in the AbstractGateway that I think should be included in the GatewayInterface (supportsAuthorize, supportsCompleteAuthorize, supportsCapture, etc...). I wanted to know peoples thoughts on this before I spent the time on a PR.
=> Annotations for optional methods on GatewayInterface

src/Omnipay/Common/CreditCard.php, tests/Omnipay/Common/CreditCardTest.php
There are payment services like 2checkout (https://www.2checkout.com/documentation/payment-api/create-sale#) that also collect phone number extension besides the phone number.
This PR adds support for it.
=> Added phone extension support to CreditCard object

src/Omnipay/Common/Message/AbstractRequest.php
Fix AbstractRequest::validate() so that it does not throw an exception on parameters with a zero value.
=> alternate fix for PR 64

composer.json, src/Omnipay/Common/AbstractGateway.php, src/Omnipay/Common/CreditCard.php, src/Omnipay/Common/Customer.php, src/Omnipay/Common/HasParametersTrait.php, src/Omnipay/Common/Helper.php, src/Omnipay/Common/Item.php, src/Omnipay/Common/Message/AbstractRequest.php, src/Omnipay/Common/ParameterizedInterface.php, tests/Omnipay/Common/AbstractGatewayTest.php, tests/Omnipay/Common/CreditCardTest.php, tests/Omnipay/Common/CustomerTest.php, tests/Omnipay/Common/HelperTest.php
Two main things here:
1. Abstract Parameter manipulation. This is duplicated all over the place and it bugs me. We can make use of traits now, so we should. 
2. Customer object. This is something I've wanted to do for a long time. This will allow us to start implementing Bank Account features in 3.0 as well as making the Credit Card object much cleaner. This is my first stab at it. I'm happy to hear feedback on any of this.
=> [3.0]: Abstract Customer object

src/Omnipay/Common/Amount.php, src/Omnipay/Common/Currency.php, src/Omnipay/Common/Message/AbstractRequest.php, tests/Omnipay/Common/AmountTest.php, tests/Omnipay/Common/CurrencyTest.php, tests/Omnipay/Common/Message/AbstractRequestTest.php
See https://github.com/thephpleague/omnipay/issues/322
Breaking change; input Amount parameter is now an integer (or string representing an integer), instead of a float.
Prevent rounding/converting issues. The `getAmountInteger` is removed (as this is the default now) and a new `getAmountFloat` is added, for the old behaviour. Omnipay users would need to update their code for this.
A Money object (from https://github.com/moneyphp/money) is allows for `setMoney()`, which then sets the amount/currency on the request.
=> [3.0] Use integer for Amount instead of float

src/Omnipay/Common/CreditCard.php, tests/Omnipay/Common/CreditCardTest.php
Authorize.Net and Stripe are examples of gateways that support card present transactions i.e. they accept raw track data from the credit card's magnetic strip. In order to support this, the `CreditCard` object needs a few tweaks to be able to store this track information.
=> Support for card present transactions

composer.json
This allows apps/teams to move to Symfony3. Without it, upgrading is
impossible due to restrictions on using Http Foundation from 2.x series.
This is same PR as #97, but only has allowance of HttpFoundation from 3.x series, without extra jobs to run.
=> Allow Symfony 3 HttpFoundation

.travis.yml, composer.json
- Use cache to improve speed
- Build lowest + stable builds for 5.3 (symfony2) and 5.5 (symfony3). 
- Normal builds for rest
- Reduces number of builds (24 -> 10) and build time
=> Use cache, prefer-lowest/stable instead of specific versions

src/Omnipay/Common/CreditCard.php, tests/Omnipay/Common/CreditCardTest.php
Improved coverage that fixes #87 (builds upon #88)
For example, card numbers starting with `22x` (where `x` was not 1 or 2, e.g. `2230 xxxx xxxx xxxx`) were not handled properly.
Updated test case to reflect the new coverage, as well as add missing test coverage for Mastercard 677189 BINs.
_(Thanks to @slashP for the notice, and @delatbabel for followup regex tests!)_
=> Fix MasterCard "2" series BIN range support

src/Omnipay/Common/Message/AbstractRequest.php, tests/Omnipay/Common/Message/AbstractRequestTest.php
Previously, if you set the currency field for a request to null via `AbstractRequest::setCurrency` or did not set it at all initially and then called `validate` on the currency field, the validation would pass because `strtoupper(null) === ''`, but `validate` looks for null values (via `isset`) when determining what should fail.
Now `strtoupper` is not called when the currency field is set to null, so the field is actually null instead of `''` and validation will fail appropriately.
=> Fix bug where validating currency field passes after setting the currency to null

src/Omnipay/Common/CreditCard.php
They claim to return strings but actually return ints because the setters cast everything
=> Fix return types on card date functions

composer.json, src/Http/AbstractClient.php, src/Http/ClientInterface.php, src/Http/Factory.php, src/Http/GuzzleClient.php, src/Message/AbstractResponse.php, tests/AbstractGatewayTest.php, tests/Http/AbstractClientTest.php, tests/Http/FactoryTest.php, tests/Http/GuzzleClientTest.php
- Since Guzzle supports ServerRequestFactory from Globals, we don't need to use Diactoros.
- The [HTTP Factory PSR](https://github.com/php-fig/fig-standards/blob/master/proposed/http-factory/http-factory.md) seems to be stalled, so I created my own factory with similar methods.
- The HttpClient should just be sending methods, not other PSR factories. So split those out.
- Add shortcuts for get/post/put etc in an AbstractClient, for easier upgrade and readability.
- Use static calls for the factories, as I don't think these need to be changed in user-land and don't require state.
I think this cleans up the factories pretty well, as we don't need to inject a lot of dependancies everywhere. Note that we do require on Guzzle/psr7 for this, but only internally, so we can upgrade to other PSR-7 …
=> [3.0] Add HTTP Factories for Guzzle

composer.json, src/Omnipay/Common/Http/Client.php, src/Omnipay/Common/Http/ResponseParser.php, tests/Omnipay/Common/Http/ClientTest.php, tests/Omnipay/Common/Http/ResponseParserTest.php
Makes it easier to upgrade; `null` headers is allowed an body is converted by default.
Renamed the Decoder to ResponseParser.
Added some tests
=> [3.0] Add convenience helpers, rename decoder, add tests

src/Common/Message/AbstractRequest.php, tests/Omnipay/Common/Message/AbstractRequestTest.php
See https://github.com/thephpleague/omnipay-common/issues/143
Eg. for large numbers, the rounding doesn't work (> 8 number before comma).
TOdo
=> Account for large amounts

src/Common/GatewayInterface.php
Add Comments of return data type on GatewayInterface so my IDE can hint me when I wrote code like `$gateway=new Omnipay('xxPayType'); $gateway->initialize($config)->someOperation($params);`
=> Add Comments of return data type

src/Common/CreditCard.php, tests/Omnipay/Common/CreditCardTest.php
When missing a required parameter for credit cards
the exception message uses the key value in the
array instead of a more standard value.
resolves #169
=> Clarify exception message for credit cards

src/Common/Message/AbstractRequest.php, tests/Omnipay/Common/Message/AbstractRequestTest.php
This adds a method to set the amount as integer. Can be useful in case you're already using integer-based objects (eg. Money) instead of relying on the interfaces/objects directly (see https://github.com/thephpleague/omnipay-common/commit/cda8afc670d93e51d4a5d0676732206a230e5d4c which removed Money public support)
=> Allow to set amount as integer

.travis.yml, composer.json, phpunit.xml.dist, src/Common/Http/Client.php, src/Common/Http/ClientInterface.php, src/Common/Http/Exception.php
If this installs correctly, no need to use 7.1 while 5.6 is still on security support.
=> Allow PHP 5.6 and 7.0 to be installed

src/Common/AbstractGateway.php, src/Common/CreditCard.php, src/Common/Item.php, src/Common/Message/AbstractRequest.php, src/Common/ParametersTrait.php, tests/Omnipay/Common/CreditCardTest.php
Uses trait for the parameters to clean up the parameter stuff. Based on #80
=> Use ParameterTrait

src/Common/AbstractGateway.php, src/Common/GatewayInterface.php, tests/Omnipay/Common/AbstractGatewayTest.php
Hi!
`AbstractGateway` has a `supportsAcceptNotification()` method, but `acceptNotification()` is not in the interface as optional method. Not sure if this is on purpose, but I feel like it should be there.
And as far as I can tell, `fetchTransaction()` is normally used to fetch transaction info, but it's not currently in the interface / AbstractGateway either.
=> Add supportsFetchTransaction, fetchTransaction, and acceptNotification methods

src/Common/AbstractGateway.php, src/Common/ParametersTrait.php, tests/Omnipay/Common/AbstractGatewayTest.php
These shouldn't be protected but public. Tests are fixed to pick this error up.
Fixes #217
=> Make set/getParameter public on Gateway

src/Common/Message/AbstractResponse.php
Hi,
Just a small change to avoid the symfony deprecation error (trigger_deprecated) for the static "create" methods.
=> corrects deprecated symfony 5.1

src/Common/Helper.php, tests/Common/HelperTest.php
See : https://github.com/thephpleague/omnipay/issues/650
=> allowing Classname::class syntax for getGatewayClassName()

composer.json
@barryvdh unsure about how this can be properly tested, besides pre-existing tests: ideally, `vimeo/psalm` should be included in the toolchain :thinking:
=> Allow usage of `moneyphp/money:^4.0.3`

.github/workflows/phpunit.yml
fix deprecation of github action versions
=> chore: bump github actions for "actions/checkout" 2 => 4

.github/workflows/phpunit.yml
Run composer update --prefer-lowest --no-interaction --no-progress --no-suggest
You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
=> ci: run --prefer-lowest run only for lowest supported PHP version

src/Common/Http/Client.php
Also the function `GuzzleHttp\Psr7\str` is removed from `guzzle/psr7` v2.0
=> Remove unused imported function and interface

src/Common/CreditCard.php, src/Common/Helper.php, src/Common/Message/AbstractResponse.php, tests/Common/GatewayFactoryTest.php, tests/Common/ItemBagTest.php, tests/Common/ItemTest.php
Cast value to string. It would be better to check for null but the typehint suggest is should be `string`. So keeping types as-is.
Fixes #260
=> Fix deprecated issues

.github/workflows/phpunit.yml, phpunit9.xml.dist
CI was failing on #275 due to higher versions of PHP using newer versions of PHPUnit, which has a different XML configuration file format. This should fix just the CI runner process to allow for that.
=> Add support for PHPUnit 10+ to CI process
